### ISSUE TITLE
Hi,dev,I can't run tsiv's ccminer under win8.1.Driver crashes.

### ISSUE THREAD

**Issue by hero18688** [tsiv/ccminer-cryptonight#1]
I can't run tsiv's ccminer under win8.1.Driver crashes everytime I start ccminer.Any solution?
[IMG]http://i.imgur.com/csCbTnE.png[/IMG]

**Comment by hero18688** [comment]
No problem mining other algos

**Comment by tsiv** [comment]
Smells like TDR, have you tried the latest build?

**Comment by tsiv** [comment]
Assuming fixed by latest release, closing.

**Comment by hero18688** [comment]
ok after add -l parameters

2014-07-23 13:32 GMT+08:00 tsiv notifications@github.com:
